### PR TITLE
Fix Find Command Issues

### LINKED ISSUE #236: [PE-D][Tester C] Use cases for archive / unarchive commands
The developer guide has use cases for almost every command (undo/redo can count as one), however the archive command is left out, which may leave future devlopers confused on 1) why it was left out 2) how does the operation work in different scenarios

-------------
Labels: `severity.Low` `type.DocumentationBug`

### LINKED ISSUE #269: [PE-D][Tester B] Issue in archive command section
Image
I think the the "what is archiving" sub topic does not match what is specified below it, it is best to probably change it to something like "points to note" or something better.

-------------
Labels: `severity.Low` `type.DocumentationBug`

### LINKED ISSUE #271: [PE-D][Tester B] Issue in archive command section
Image
The 3rd point under "what is archiving?" might be a bit ambiguous to reader, it is best to state "you may view archived recruits using list -archived or all recruits including archived ones using list -all" though you have stated the differences in these command earlier in the list section.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`

### LINKED ISSUE #277: [PE-D][Tester C] Find Command doesnt parse valid inputs (no response)
Image

Here are the exact steps I took to reproduce this error:

1. add n/peter, to create a new contact and create the success message  
2. find -id 11

which causes no response from the app (no error message etc)

Then when i scroll down, i get an empty list, like so:

Image

This seems like an error, since even if the command format was incorrect (however i think it is, since find -id 123 was allowed in the user guide), the user should receive a corresponding error message.

For reference, I got this in the terminal.
Image

-------------
Labels: `severity.High` `type.FunctionalityBug`

### LINKED ISSUE #304: [PE-D][Tester D] find -id does not match UUID substrings despite UG saying “contain any of the specified keywords”
## Preconditions:
At least one recruit exists so that its UUID is visible on the card (e.g., 9f264523-fef7-4188-aaf5-5387f26a0a7).

## Steps to reproduce:
Launch the app:
```
java -jar TalentNexus.jar
```

Copy a recruit’s UUID from the UI.

Search using a substring of that UUID (e.g., first 8 chars):
```
find -id 9f264523
```

(Control) Search using the full UUID:
```
find -id 9f264523-fef7-4188-aaf5-5387f26a
```

## Expected
Per find description, the command “Finds all recruits who contain any of the specified keywords (case-insensitive).”

Therefore, find -id 9f264523 should return the recruit whose UUID contains that substring (same behavior as name/phone/address substring matching).

## Actual
find -id <substring> returns no results (or shows “Invalid command format!”), while find -id <full-uuid> works.

Substring matching for UUIDs is not honored, contradicting the stated “contain keywords” behavior.

## Evidence

Image

Image

## UG Reference
find command help in-app:

“Finds all recruits who contain any of the specified keywords (case-insensitive)… Parameters: -id for ID … Example: find -n alice|bob|charlie -a Clementi -p 98765432
(The term contain implies substring matching, not exact/full-only match.)

## Rationale
Users often copy only part of an ID for quick lookup; failing to match substrings makes find -id inconsistent with the documented semantics and with other fields that support partial matches.

## Justification for severity:
Search reliability is core functionality. While the app doesn’t crash, this mismatch impairs normal usage → severity.Medium.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by shriniket03**
Find Command had a few reported issues during the PE-D

This PR seeks to resolve it

Closes #277 
Closes #304 
Closes #271 
Closes #269 
Closes #236

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/FindCommandParser.java
Comment (iZUMi-kyouka) [inline src/main/java/seedu/address/logic/parser/FindCommandParser.java]: This seems to be related to the pipe operator. Refer to telegram chat.

**Review by iZUMi-kyouka — APPROVED** [review]
LGTM, but HelpWindow.,java has not been modified

File: docs/UserGuide.md [hunk 1]
```diff
@@ -370,56 +370,56 @@ Examples usage scenario:
 
 Finds all recruits whose details match any of the given keywords.
 
-Format: `find NAME [-id KEYWORDS] [-n KEYWORDS] [-p KEYWORDS] [-e KEYWORDS] [-a KEYWORDS] [-t KEYWORDS]`
+Format: `find NAME [id/ KEYWORDS] [n/ KEYWORDS] [p/ KEYWORDS] [e/ KEYWORDS] [a/ KEYWORDS] [t/ KEYWORDS]`
```
Comment (Eilyss) [inline docs/UserGuide.md]: I think remove the space between id/KEYWORDS

**Review by Eilyss — CHANGES_REQUESTED** [review]
I think the only change necessary is in the UG, the KEYWORDS should stick to the id/ to indicate that the space is not necessary
